#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""UI fragments for long-term reading career views on GitHub Pages.

The module is intentionally data-free. It consumes the already embedded report
objects (D and E) and adds deterministic visualizations without raw note text.
"""

import pages_year_lens_ui

CSS = r'''
.career-svg,.scatter-svg,.evolution-svg{width:100%;height:auto;display:block}.chart-axis{stroke:var(--line);stroke-width:1}.chart-grid{stroke:color-mix(in srgb,var(--line) 65%,transparent);stroke-width:1}.chart-line{fill:none;stroke:var(--accent);stroke-width:3}.chart-area{fill:color-mix(in srgb,var(--accent) 13%,transparent)}.chart-label{fill:var(--muted);font-size:10px}.chart-value{fill:var(--ink);font-size:11px;font-weight:700}.scatter-dot{fill:var(--accent2);fill-opacity:.72;stroke:var(--paper);stroke-width:1}.scatter-secret{fill:var(--accent);fill-opacity:.82}.scatter-month{fill:var(--accent3);fill-opacity:.75;stroke:var(--paper);stroke-width:1}.trend-line{stroke:var(--accent);stroke-width:1.5;stroke-dasharray:5 4}.year-chapters{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.year-card{border:1px solid var(--line);border-radius:18px;padding:16px;min-height:150px;position:relative;overflow:hidden}.year-card:before{content:attr(data-year);position:absolute;right:-4px;bottom:-18px;font-size:76px;line-height:1;color:color-mix(in srgb,var(--line) 38%,transparent);font-weight:800;pointer-events:none}.year-card h3{font-size:25px;margin:0 0 8px}.year-kpis{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}.year-kpis span{font-size:10px;border:1px solid var(--line);border-radius:999px;padding:4px 7px}.year-card p{font-size:11px;color:var(--muted);margin:4px 0;max-width:85%;position:relative}.evolution-bars{display:grid;gap:12px}.evo-row{display:grid;grid-template-columns:54px 1fr 76px;gap:10px;align-items:center;font-size:11px}.evo-track{height:18px;background:var(--line);border-radius:999px;overflow:hidden;display:flex}.evo-mark{background:var(--accent2);height:100%}.evo-review{background:var(--accent3);height:100%}.evo-legend{display:flex;gap:14px;color:var(--muted);font-size:10px;margin-top:10px}.evo-legend i{width:9px;height:9px;border-radius:2px;display:inline-block;margin-right:5px}.chart-note{font-size:11px;color:var(--muted);margin-top:10px}.scatter-pair{display:grid;grid-template-columns:1fr 1fr;gap:16px}.scatter-panel{border:1px solid var(--line);border-radius:16px;padding:14px}.scatter-panel h3{font-size:14px;margin:0 0 4px}.scatter-panel p{font-size:10px;color:var(--muted);margin:0 0 8px}
@media(max-width:900px){.year-chapters{grid-template-columns:repeat(2,1fr)}.scatter-pair{grid-template-columns:1fr}}@media(max-width:520px){.year-chapters{grid-template-columns:1fr}}
'''

HTML = r'''
  <article class="card wide" id="career"><div class="title"><div><div class="section-kicker">Reading career</div><h2>累计阅读生涯</h2></div><small>月度时长累积，不把短期波动误读成趋势</small></div><svg id="careerChart" class="career-svg" viewBox="0 0 1040 300" role="img" aria-label="累计阅读小时"></svg><div class="year-chapters" id="yearChapters"></div></article>
  <article class="card wide" id="depth-matrix"><div class="title"><div><div class="section-kicker">Depth matrix</div><h2>阅读投入的两个坐标系</h2></div><small>书籍进度 × 笔记深度；月份时长 × 笔记产出</small></div><div class="scatter-pair"><div class="scatter-panel"><h3>进度 × 笔记深度</h3><p>仅使用有已知进度的书；纵轴为 log(1 + 笔记数)，避免少数重笔记书压扁其它点。</p><svg id="bookDepthScatter" class="scatter-svg" viewBox="0 0 500 330" role="img" aria-label="阅读进度和笔记数散点"></svg></div><div class="scatter-panel"><h3>月度时长 × 笔记量</h3><p>每个点是一月；虚线仅为线性趋势辅助，Pearson r 仍不代表因果关系。</p><svg id="monthDepthScatter" class="scatter-svg" viewBox="0 0 500 330" role="img" aria-label="月度阅读时长和笔记量散点"></svg></div></div></article>
  <article class="card wide" id="note-evolution"><div class="title"><div><div class="section-kicker">Note evolution</div><h2>划线 → 想法：记录方式的年度变化</h2></div><small>想法是本人书写；划线只是保存的原文</small></div><div class="evolution-bars" id="noteEvolution"></div><div class="evo-legend"><span><i style="background:var(--accent2)"></i>划线</span><span><i style="background:var(--accent3)"></i>想法</span></div></article>
'''

JS = r'''
// Long-term career curve.
function drawCareer(){const svg=$('careerChart'),rows=(D.monthly||[]).filter(x=>(+x.hours||0)>=0);if(!svg||!rows.length)return;const W=1040,H=300,p={l:48,r:22,t:22,b:34};let cumulative=0;const pts=rows.map(x=>{cumulative+=+x.hours||0;return {...x,cumulative}}),max=Math.max(1,...pts.map(x=>x.cumulative)),dx=(W-p.l-p.r)/Math.max(1,pts.length-1),y=v=>p.t+(H-p.t-p.b)*(1-v/max),xy=pts.map((x,i)=>[p.l+i*dx,y(x.cumulative)]);let out='';for(let i=0;i<=4;i++){const yy=p.t+(H-p.t-p.b)*i/4,val=max*(1-i/4);out+=`<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" class="chart-grid"/><text x="${p.l-8}" y="${yy+4}" text-anchor="end" class="chart-label">${val.toFixed(0)}h</text>`}const path=xy.map((q,i)=>(i?'L':'M')+q[0].toFixed(1)+','+q[1].toFixed(1)).join(' '),area=path+` L${xy[xy.length-1][0]},${H-p.b} L${xy[0][0]},${H-p.b} Z`;out+=`<path d="${area}" class="chart-area"/><path d="${path}" class="chart-line"/>`;const step=Math.max(1,Math.floor(pts.length/6));pts.forEach((x,i)=>{if(i%step===0||i===pts.length-1)out+=`<text x="${xy[i][0]}" y="${H-10}" text-anchor="middle" class="chart-label">${esc(x.month)}</text>`});out+=`<text x="${W-p.r}" y="${p.t+12}" text-anchor="end" class="chart-value">累计 ${cumulative.toFixed(1)} 小时</text>`;svg.innerHTML=out}drawCareer();
// Year chapters join annual totals with focus-shift evidence.
const focusByYear=Object.fromEntries(((D.insights||{}).focusShift||[]).map(x=>[String(x.year),x]));$('yearChapters').innerHTML=(D.annual||[]).map(y=>{const f=focusByYear[String(y.year)]||{},top=(f.topCategories||[])[0],a=(f.topAuthor||{}).author;return `<div class="year-card" data-year="${esc(y.year)}"><h3>${esc(y.year)}</h3><div class="year-kpis"><span>${Number(y.hours||0).toFixed(1)}h</span><span>${y.days||0} 天</span><span>${(+y.notes||0).toLocaleString()} 笔记</span></div><p>${top?`关注最多：<b>${esc(top.category)}</b>（${top.notes} 条）`:'暂无类别时间证据'}</p><p>${a&&a!=='—'?`年度高频作者：<b>${esc(a)}</b>`:'暂无作者证据'}</p><p>本人想法占比：${Number(f.reviewRate||0).toFixed(1)}%</p></div>`}).join('');
// Generic scatter renderer.
function drawScatter(svgId,rows,xv,yv,tooltip,secretAware=false,trend=false){const svg=$(svgId);if(!svg||!rows.length){if(svg)svg.innerHTML='<text x="20" y="35" class="chart-label">暂无足够数据</text>';return;}const W=500,H=330,p={l:48,r:20,t:18,b:40},maxX=Math.max(1,...rows.map(x=>+xv(x)||0)),maxY=Math.max(1,...rows.map(x=>+yv(x)||0)),sx=v=>p.l+(W-p.l-p.r)*(+v||0)/maxX,sy=v=>H-p.b-(H-p.t-p.b)*(+v||0)/maxY;let out='';for(let i=0;i<=4;i++){const xx=p.l+(W-p.l-p.r)*i/4,yy=p.t+(H-p.t-p.b)*i/4;out+=`<line x1="${xx}" y1="${p.t}" x2="${xx}" y2="${H-p.b}" class="chart-grid"/><line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" class="chart-grid"/>`;}if(trend&&rows.length>=3){const xs=rows.map(x=>+xv(x)||0),ys=rows.map(x=>+yv(x)||0),mx=xs.reduce((a,b)=>a+b,0)/xs.length,my=ys.reduce((a,b)=>a+b,0)/ys.length,den=xs.reduce((s,x)=>s+(x-mx)*(x-mx),0),slope=den?xs.reduce((s,x,i)=>s+(x-mx)*(ys[i]-my),0)/den:0,inter=my-slope*mx,y0=Math.max(0,inter),y1=Math.max(0,inter+slope*maxX);out+=`<line x1="${sx(0)}" y1="${sy(y0)}" x2="${sx(maxX)}" y2="${sy(y1)}" class="trend-line"/>`;}rows.forEach(r=>{const cx=sx(xv(r)),cy=sy(yv(r)),cls=secretAware&&r.secret?'scatter-dot scatter-secret':trend?'scatter-month':'scatter-dot';out+=`<circle cx="${cx}" cy="${cy}" r="5" class="${cls}"><title>${esc(tooltip(r))}</title></circle>`});out+=`<text x="${W/2}" y="${H-8}" text-anchor="middle" class="chart-label">${secretAware?'阅读进度 %':'月度阅读小时'}</text>`;svg.innerHTML=out}
const knownBooks=(E.bookshelf||[]).filter(b=>b.progress!==null&&b.progress!==undefined);drawScatter('bookDepthScatter',knownBooks,b=>b.progress,b=>Math.log1p(+b.noteCount||0),b=>`${b.title} · ${b.progress}% · ${b.noteCount} 条笔记`,true,false);
const corrMonths=((E.correlation||{}).months||[]).filter(x=>(+x.hours||0)>0||(+x.notes||0)>0);drawScatter('monthDepthScatter',corrMonths,x=>x.hours,x=>x.notes,x=>`${x.month} · ${Number(x.hours).toFixed(1)}h · ${x.notes} 条笔记`,false,true);
// Mark/review composition by year.
const evo=((D.insights||{}).focusShift||[]),maxNotes=Math.max(1,...evo.map(x=>+x.notes||0));$('noteEvolution').innerHTML=evo.map(x=>{const total=+x.notes||0,marks=+x.marks||0,reviews=+x.reviews||0,width=100*total/maxNotes,markPct=total?100*marks/total:0,reviewPct=total?100*reviews/total:0;return `<div class="evo-row"><b>${esc(x.year)}</b><div class="evo-track" style="width:${Math.max(4,width)}%"><div class="evo-mark" style="width:${markPct}%"></div><div class="evo-review" style="width:${reviewPct}%"></div></div><span>${reviews} / ${total}</span></div>`}).join('')||'<p class="muted">暂无年度笔记数据。</p>';
'''

# Compose the interactive year lens ahead of the static career sections.
CSS = pages_year_lens_ui.CSS + "\n" + CSS
HTML = pages_year_lens_ui.HTML + "\n" + HTML
JS = JS + "\n" + pages_year_lens_ui.JS
